### ISSUE TITLE
set_channel function not working

### ISSUE THREAD

**Issue by jneidhart1** [firstone/RESTRemote#2]
Getting an error when trying to use the set channel function:
   command.get('value'))
  File "/var/polyglot/nodeservers/AVRemote/drivers/base_driver.py", line 107, in executeCommand
    result['output'] = self.sendCommandRaw(commandName, command, args)
  File "/var/polyglot/nodeservers/AVRemote/drivers/tivo_ip.py", line 30, in sendCommandRaw
    conn.send(command['code'].encode())
KeyError: 'code'

**Comment by jneidhart1** [comment]
appears the tivo_ip.py is having issues with extra parameters being sent with the set_channel button.   not working when commands are added into the command[code] string.

**Comment by firstone** [comment]
I will take a look but need a few days

**Comment by jneidhart1** [comment]
import socket
import time

from drivers.base_driver import BaseDriver


class TivoIP(BaseDriver):

    RECEIVE_BUFFER_SIZE = 1024

    def __init__(self, config, logger, use_numeric_key=False):
        super(TivoIP, self).__init__(config, logger, use_numeric_key)

        logger.info('Loaded %s driver', self.__class__.__name__)

    def connect(self):
        conn = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        conn.connect((self.config['hostName'], self.config['port']))
        conn.settimeout(self.config['timeout'])
        conn.close()
        self.connected = True

    def sendCommandRaw(self, commandName, command, args=None):
        result = ''
        conn = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            conn.connect((self.config['hostName'], self.config['port']))
            conn.settimeout(self.config['timeout'])
            self.logger.info('conn.send commandName = %s, command= %s', commandName, command)
            self.logger.info('conn.send command[keys] = %s', command.keys())
            self.logger.info('conn.send command[values] = %s', command.values())
            self.logger.info('sendCommandRaw.args = %s', args)

            for key in command:
                if key == 'commands':
                    self.logger.info('for key:%s in command = %s', key, command[key][0]['code'])
                    conn.send(command[key][0]['code'].encode())
                    self.logger.info('%s Sends %s', key, command[key][0]['code'])
                    if (command[key][0].get('argument') or 'value_set' in command) and args:
                        conn.send(args.encode())
                        self.logger.info('%s Args Sends %s', key, args)
                    conn.send('\r'.encode())
                    if command[key][0].get('response', False):
                        result = conn.recv(TivoIP.RECEIVE_BUFFER_SIZE).decode()
                        self.logger.info('%s result = %s', key, result)
                    delay = command[key][0].get('delay')
                    if delay:
                        time.sleep(delay)

                    self.logger.info('for key:%s in command = %s', key, command[key][1]['code'])
                    cmdstr = command[key][1]['code']
                    if cmdstr == 'SETCH ':
                        channelstr = ""
                        for x in args:
                            channelstr = channelstr + 'IRCODE '  + 'NUM' + x + '\r'
                        channelstr = channelstr + 'IRCODE ENTER\r'
                        conn.send(channelstr.encode())
                        self.logger.info('%s Sends %s', key, channelstr)
                    else:
                        conn.send(command[key][1]['code'].encode())
                        self.logger.info('%s Sends %s', key, cmdstr)

                        if (command[key][1].get('argument') or 'value_set' in command) and args:
                             conn.send(args.encode())
                             self.logger.info('%s Args Sends %s', key, args)

                    conn.send('\r'.encode())
                    if command[key][1].get('response', False): 
                        result = conn.recv(TivoIP.RECEIVE_BUFFER_SIZE).decode()
                        self.logger.info('%s result = %s', key, result)
                    delay = command[key][1].get('delay')
                    if delay:
                        time.sleep(delay)

                if key == 'code':
                    self.logger.info('for key:%s in command = %s', key, command['code'])
                    conn.send(command['code'].encode())
                    if (command.get('argument') or 'value_set' in command) and args:
                        conn.send(args.encode())
                        self.logger.info('%s Args Sends %s', key, args)
                    conn.send('\r'.encode())
                    if command.get('response', False):
                        result = conn.recv(TivoIP.RECEIVE_BUFFER_SIZE).decode()
                        self.logger.info('%s result = %s', key, result)
                    delay = command.get('delay')
                    if delay:
                        time.sleep(delay)

        except socket.timeout:
            pass
        conn.close()
        return result

**Comment by jneidhart1** [comment]
I was able to make changes to your tivo_ip.py to get this to work.  You can use what you want from my changes.   I have a Tivo Mini , bolt and edge.  Was not able to get SETCH command to work.  Would just return error.   So changed to using IRCODE numbers instead.  Appears to be working now.   Also change LIVETV to use TELEPORT command instead of IRCODE.  IRCODE LIVETV cause tuner change when already in livetv mode where TELEPORT LIVETV does not.

**Comment by jneidhart1** [comment]
Left logger info lines inside code so you can run and easily follow the execution.   Got busy in order to parse the  dictionary command string passed to it.

**Comment by firstone** [comment]
I've fixed original issue in my repo. But SETCH still isn't working. I guess tivo changed something in the protocol. I'll see how to fix it better.

**Comment by jneidhart1** [comment]
pulled over your tivo_ip.py off the dev branch but now gives the error below:

2022-01-11 12:51:42,946 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Connected with result code 0 (Success)
2022-01-11 12:51:42,948 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Subscribing to topic: udi/polyglot/ns/3 -  MID: 1 Result: 0
2022-01-11 12:51:42,948 MQTT       polyinterface      INFO     polyinterface:_connect: MQTT Subscribing to topic: udi/polyglot/connections/polyglot -  MID: 2 Result: 0
2022-01-11 12:51:42,949 MQTT       polyinterface      INFO     polyinterface:_connect: Sent Connected message to Polyglot
2022-01-11 12:51:42,970 MQTT       polyinterface      INFO     polyinterface:_subscribe: MQTT Subscribed Succesfully for Message ID: 1 - QoS: (0,)
2022-01-11 12:51:42,981 MQTT       polyinterface      INFO     polyinterface:_subscribe: MQTT Subscribed Succesfully for Message ID: 2 - QoS: (0,)
2022-01-11 12:51:43,116 NodeServer polyinterface      INFO     polyinterface:save_typed_params: Sending typed parameters to Polyglot.
2022-01-11 12:51:43,405 MQTT       polyinterface      ERROR    polyinterface:_message: MQTT Received Unknown Error: An exception of type AttributeError occured. Arguments:
("type object 'TivoIP' has no attribute 'processParams'",)
Traceback (most recent call last):
  File "/var/polyglot/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 270, in _message
    self.inConfig(parsed_msg[key])
  File "/var/polyglot/.local/lib/python3.7/site-packages/polyinterface/polyinterface.py", line 501, in inConfig
    watcher(config)
  File "/var/polyglot/nodeservers/AVRemote/poly/remotecontroller.py", line 42, in process_config
    if self.get_device_driver(deviceDriverName, driverData).processParams(
AttributeError: type object 'TivoIP' has no attribute 'processParams'

Is there more I need to update besides tivo_ip.py?

**Comment by firstone** [comment]
processParams is defined in BaseDriver. You shouldn't have to explicitly define it.

"dev" bench is also likely not current. Go off master branch, it's most current.

Off topic, I cannot reliably send TELEPORT + IRCODE channel. It fails in different places. I need to write smaller test program and experiment until it works reliably.

**Comment by jneidhart1** [comment]
Are you saying I can just delete and reinstall the master code and it is fixed?
Couldn't see the difference in tivo_ip.py in that branch.   

the Teleport command works best with bolt/edge models.  Find the other models including mini to slow to work.
I changed it to where it just changes the channel without the LIVETV command each time.   Added TELEPORT LIVETV as a wakeup command.   Only use it when I want to wakeup my TIVO.   Also only need <CR> after each TIVO command doesn't require a <LF>\n.

**Comment by firstone** [comment]
> Are you saying I can just delete and reinstall the master code and it is fixed? Couldn't see the difference in tivo_ip.py in that branch.

You need to switch the branch to master. It shouldn't have that particular issue with processParams, at least.

> the Teleport command works best with bolt/edge models. Find the other models including mini to slow to work. I changed it to where it just changes the channel without the LIVETV command each time. Added TELEPORT LIVETV as a wakeup command. Only use it when I want to wakeup my TIVO. Also only need after each TIVO command doesn't require a \n.

The reason for "LIVETV" something is because if you're watching a program, sending IR number will not change the channel. You need to switch to livetv mode first. And tivo responds to LIVETV for me but then it doesn't like something and I get connection closed a lot. Just need to figure it out before I update.

**Comment by jneidhart1** [comment]
I have taken the tivo_ip.py code off your dev branch and overwrote the master branch tivo_ip.py which gave the error I showed you.   I believe the dev branch version takes care of the dictionary parsing that occured in the tivo_ip.py when you sent commands that were more than one.  Such as SETCH & FORCECH.   Server_Config.yaml show SETCH send both LIVETV & SETCH.   Will not work with master tivo_ip.py code.   I have made my own quick fix of tivo_ip.py that corrects this and also the SETCH/FORCECH.  Changed it to pass IRCODE NUM#### command instead of SETCH/FORCECH.   Since SETCH/FORCECH not working.   

I must be doing something wrong since I can't get your change running.  What exact .py files did you change for this fix?


My understanding of the LIVETV function is to put the TIVO into a live channel tuner on your TIVO.   If you are recording on the current tuner it would switch to a new tuner if available.  If you are in a menu, channel guide,  Tivo...   it would take you to a live channel tuner.   Then you can switch the channel.  Only issue is timing.   Depending on tivo box you have different delays.
I can change the channel with new code quickly by sending IRCODE NUM###\rIRCODENUM###\rIRCODE ENTER\r.
example:  IRCODE NUM1\rIRCODE NUM2\rIRCODE ENTER\r will change channel to 12 if they are  currently watchin a livetv channel or have extra tuners available.   I now only use the LIVETV function when I need it for the items I listed above.

**Comment by firstone** [comment]
I got it to work but...

TELEPORT LIVETV does not stop currently playing program. 

IRCODE LIVETV does. 

Perhaps "Set Channel" should just send channel directly.

But, "Force Set Channel" should call "IRCODE LIVETV" first, in order to quit  currently playing program, if any.

What do you think?

**Comment by jneidhart1** [comment]
I think depending on what box you have as well as additional items.  I have spectrum which requires a cablecard and tuning adapter which slows down the channel change.   So if you send a livetv command it doesn't finish before the set channel occurs and ends up not getting channel changed or to a wrong channel.    

Found this for TELE PORT: 
Change to one of the following TiVo menu screens: TIVO (Home), LIVETV, GUIDE, NOWPLAYING (My Shows), SEARCH, NETFLIX.

Was thinking you might be able to create a routine that  gets a response from the tivo looking for CH_STATUS #### LOCAL.  Showing it is in a mode that would take the channel selection.  If you don't get LOCAL you could  send the livetv.   I am using voice commands and just call wakeup tv /Go to livetv if it is not in correct mode and then change the channel. 
 
Having two different commands SETCH or FORCECH would give you the same function.  One calling LIVETV other would not.  Also would give people a choice if they want to call LIVETV each time or not.

**Comment by jneidhart1** [comment]
Saw posted new release.   Tried doing update to mine but gate repo error and said it could pull it.
Uninstalled and installed from scratch worked.

But tivo_ip.py is throwing an error now:
2022-01-13 11:49:23,364 Controller polyinterface      ERROR    base_driver:start: Connection to tivo-family.nc-services.com:31339 failed
Traceback (most recent call last):
  File "/var/polyglot/nodeservers/AVRemote/drivers/base_driver.py", line 25, in start
    self.connect()
  File "/var/polyglot/nodeservers/AVRemote/drivers/tivo_ip.py", line 17, in connect
    self.do_connect()
  File "/var/polyglot/nodeservers/AVRemote/drivers/tivo_ip.py", line 22, in do_connect
    if self.conn is not None:
AttributeError: 'TivoIP' object has no attribute 'conn'
2022-01-13 11:49:23,374 Controller polyinterface      ERROR    base_driver:start: Connection to tivo-movierm.nc-services.com:31339 failed
Traceback (most recent call last):
  File "/var/polyglot/nodeservers/AVRemote/drivers/base_driver.py", line 25, in start
    self.connect()
  File "/var/polyglot/nodeservers/AVRemote/drivers/tivo_ip.py", line 17, in connect
    self.do_connect()
  File "/var/polyglot/nodeservers/AVRemote/drivers/tivo_ip.py", line 22, in do_connect
    if self.conn is not None:
AttributeError: 'TivoIP' object has no attribute 'conn'

**Comment by jneidhart1** [comment]
FYI,

added self.conn = None
 to tivo_ip.py __init__   which fixed issue
